server:
  #  port: 8081
  port: ${SERVER_PORT}

spring:
  datasource:
#    url: jdbc:postgresql://postgres_db1:5432/personsdb
    url: ${SPRING_DATASOURCE_URL}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME}