server:
#  port: 8081
  port: ${SERVER_PORT}

spring:
  datasource:
    url: jdbc:postgresql://postgres_db1:5432/personsdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true