server:
  port: ${SERVER_PORT}

spring:
  cloud:
    gateway:
      routes:
        - id: persons-service
          uri: http://persons-service:8081
          predicates:
            - Path=/persons/**

        - id: companies-service
          uri: http://companies-service:8082
          predicates:
              - Path=/companies/**